-- Migration 005: Create LESSONS Table
-- Stores generated accessible lessons with auditory descriptions, sensory analogies, and audio pointers
CREATE TABLE IF NOT EXISTS EDUBRIDGE_ADAPTIVE.APP.LESSONS (
    lesson_id VARCHAR(64),
    id VARCHAR(64),
    textbook_asset_id VARCHAR(64),
    image_id VARCHAR(64),
    user_id VARCHAR(64) NOT NULL,
    title VARCHAR(500) NOT NULL,
    raw_text TEXT,
    structured_content VARIANT,
    summary TEXT,
    simplified_text TEXT,
    screen_reader_transcript TEXT,
    audio_asset_id VARCHAR(64),
    audio_url VARCHAR(1000) COMMENT 'Direct Cloudinary streaming URL for narration',
    audio_public_id VARCHAR(255),
    audio_duration_seconds NUMBER(10, 2) DEFAULT 0.0,
    waveform_url VARCHAR(1000) COMMENT 'Cloudinary precomputed waveform data URL',
    difficulty VARCHAR(50) DEFAULT 'beginner',
    difficulty_level VARCHAR(50) DEFAULT 'beginner',
    processing_status VARCHAR(50) DEFAULT 'COMPLETED',
    status VARCHAR(50) DEFAULT 'DRAFT' COMMENT 'Lifecycle: DRAFT, PROCESSING, PUBLISHED, ARCHIVED, FAILED',
    ai_model VARCHAR(100) DEFAULT 'gemini-1.5-flash',
    error_message TEXT,
    sensory_analogies VARIANT COMMENT 'Real-world tactile and auditory analogies generated by Gemini',
    key_takeaways VARIANT COMMENT 'Structured conceptual bullets formatted for screen readers',
    ai_generation_metadata VARIANT COMMENT 'Gemini model parameters, prompt tokens, and duration',
    created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Accessible multimodal lessons adapted for visually impaired students';
