'use client';

import React from 'react';
import Link from 'next/link';
import { PageContainer } from '../../components/shell';
import { ProtectedRoute } from '../../components/auth';
import {
  Button,
  Badge,
  Card,
  CardBody,
  Skeleton,
  EmptyState,
  ErrorState
} from '../../components/ui';
import { useLessons } from '../../hooks/useLessons';
import { LessonCard, LessonToolbar } from '../../components/lessons';
import { getReadableErrorMessage } from '../../lib/errorHandler';

export default function LessonsPage() {
  const {
    lessons,
    filteredLessons,
    availableSubjects,
    loading,
    error,
    refetch,
    searchQuery,
    setSearchQuery,
    statusFilter,
    setStatusFilter,
    subjectFilter,
    setSubjectFilter,
    audioOnlyFilter,
    setAudioOnlyFilter,
    sortBy,
    setSortBy,
    resetFilters
  } = useLessons();

  const isLibraryEmpty = !loading && !error && lessons.length === 0;
  const isSearchEmpty = !loading && !error && lessons.length > 0 && filteredLessons.length === 0;

  return (
    <ProtectedRoute>
      <PageContainer>
        <div className="stack-lg">
          {/* Header */}
          <header className="flex items-center justify-between flex-wrap gap-4">
            <div>
              <div className="flex items-center gap-2" style={{ marginBottom: 'var(--spacing-1)' }}>
                <Badge variant="primary">Snowflake & Cloudinary Synced</Badge>
                <Badge variant="accent">Piper TTS Narration</Badge>
              </div>
              <h1 className="text-h1">My Lessons</h1>
              <p className="text-body" style={{ color: 'var(--text-secondary)' }}>
                Multimodal accessible lessons generated by Gemini AI with Piper neural TTS narration and tactile analogies.
              </p>
            </div>

            <Link href="/upload">
              <Button variant="primary">
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true">
                  <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                  <polyline points="17 8 12 3 7 8" />
                  <line x1="12" y1="3" x2="12" y2="15" />
                </svg>
                <span>Upload Textbook</span>
              </Button>
            </Link>
          </header>

          {/* Search, Filter & Sort Toolbar */}
          {!loading && !error && lessons.length > 0 && (
            <LessonToolbar
              searchQuery={searchQuery}
              onSearchChange={setSearchQuery}
              statusFilter={statusFilter}
              onStatusChange={setStatusFilter}
              subjectFilter={subjectFilter}
              onSubjectChange={setSubjectFilter}
              audioOnlyFilter={audioOnlyFilter}
              onAudioOnlyChange={setAudioOnlyFilter}
              sortBy={sortBy}
              onSortChange={setSortBy}
              availableSubjects={availableSubjects}
              totalCount={lessons.length}
              filteredCount={filteredLessons.length}
              onResetFilters={resetFilters}
            />
          )}

          {/* Error State */}
          {error && !loading && (
            <ErrorState
              error={error}
              title="Unable to load your lessons"
              retryText="Retry Connection"
              onRetry={refetch}
            />
          )}


          {/* Loading Skeleton Grid */}
          {loading && (
            <section aria-busy="true" aria-label="Loading your lessons library">
              <div className="lessons-grid">
                {[1, 2, 3, 4, 5, 6].map((i) => (
                  <Card key={i}>
                    <Skeleton variant="rect" height={170} />
                    <CardBody>
                      <div className="stack-sm">
                        <Skeleton variant="text" width="40%" />
                        <Skeleton variant="text" width="85%" />
                        <Skeleton variant="text" width="60%" />
                        <div style={{ margin: 'var(--spacing-3) 0' }}>
                          <Skeleton variant="rect" height={60} />
                        </div>
                        <Skeleton variant="rect" height={40} width="100%" />
                      </div>
                    </CardBody>
                  </Card>
                ))}
              </div>
            </section>
          )}

          {/* 1. Global Zero Lessons Empty State */}
          {isLibraryEmpty && (
            <EmptyState
              title="No lessons in your library yet"
              description="Upload your first textbook page scan to generate multimodal accessible lessons with tactile analogies, Piper neural speech, and adaptive quizzes."
              icon={
                <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true">
                  <path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20" />
                  <path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z" />
                </svg>
              }
              action={
                <Link href="/upload">
                  <Button variant="primary" size="lg">
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true">
                      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                      <polyline points="17 8 12 3 7 8" />
                      <line x1="12" y1="3" x2="12" y2="15" />
                    </svg>
                    <span>Upload your first textbook page</span>
                  </Button>
                </Link>
              }
            />
          )}

          {/* 2. Filter/Search Zero Results Empty State */}
          {isSearchEmpty && (
            <EmptyState
              title="No matching lessons found"
              description={`We couldn't find any lessons matching "${searchQuery}" with the selected filters.`}
              icon={
                <svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true">
                  <circle cx="11" cy="11" r="8" />
                  <line x1="21" y1="21" x2="16.65" y2="16.65" />
                </svg>
              }
              action={
                <Button variant="outline" onClick={resetFilters}>
                  Clear Search & Filters
                </Button>
              }
            />
          )}

          {/* 3. Responsive Lessons Grid */}
          {!loading && !error && filteredLessons.length > 0 && (
            <main id="main-content" tabIndex={-1}>
              <div className="lessons-grid">
                {filteredLessons.map((lesson) => (
                  <LessonCard key={lesson.id} lesson={lesson} />
                ))}
              </div>
            </main>
          )}
        </div>
      </PageContainer>
    </ProtectedRoute>
  );
}
